# Discord settings:

bot_token: 
client_id: 

status_message: 

allow_dms: true
allowed_channel_ids: []
allowed_role_ids: []
blocked_user_ids: []

max_text: 100000
max_images: 5
max_messages: 500

use_plain_responses: # true/false

# Database settings:

neo4j:
  uri: ""
  username: ""
  password: ""

max_context_age_days: 100

# LLM settings:

providers:
  openai:
    base_url: https://api.openai.com/v1
    api_key: 
  x-ai:
    base_url: https://api.x.ai/v1
    api_key: 
  mistral:
    base_url: https://api.mistral.ai/v1
    api_key: 
  groq:
    base_url: https://api.groq.com/openai/v1
    api_key: 
  openrouter:
    base_url: https://openrouter.ai/api/v1
    api_key: 
  ollama:
    base_url: http://localhost:11434/v1
  lmstudio:
    base_url: http://localhost:8888/api/v0
  vllm:
    base_url: http://localhost:8000/v1
  oobabooga:
    base_url: http://localhost:5000/v1
  jan:
    base_url: http://localhost:6969/v1

model:    # [provider]/[model]

extra_api_parameters:
  max_tokens: 
  temperature: 

system_prompt: >